version: '3'
services:
  nginx:
    build:
      context: ./nginx-docker/./
    image: clamschowder:latest
    volumes:
      - ./nginx-docker/index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
