#Use an official Python runtime as the base image
FROM python:3.10-slim

#Set working directory in container
WORKDIR /app

#Copy requirements file into container
COPY requirements.txt /app/requirements.txt

#Copy application code to container
COPY . .

